function S1() {
    document.getElementById("maincontainer-s1").style.display = "block";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "block";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.add("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S2() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "block";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "block";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.add("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S3() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "block";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "block";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.add("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S4() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "block";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "block";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.add("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S5() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "block";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "block";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "block";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.add("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S6() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "block";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "block";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.add("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S7() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "block";
    document.getElementById("maincontainer-s8").style.display = "none";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "block";
    document.getElementById("img-qs-s8").style.display = "none";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.add("active");
    var element = document.getElementById("boton-s8");
    element.classList.remove("active");

};
function S8() {
    document.getElementById("maincontainer-s1").style.display = "none";
    document.getElementById("maincontainer-s2").style.display = "none";
    document.getElementById("maincontainer-s3").style.display = "none";
    document.getElementById("maincontainer-s4").style.display = "none";
    document.getElementById("maincontainer-s5").style.display = "none";
    document.getElementById("maincontainer-s6").style.display = "none";
    document.getElementById("maincontainer-s7").style.display = "none";
    document.getElementById("maincontainer-s8").style.display = "block";
    document.getElementById("img-qs-s1").style.display = "none";
    document.getElementById("img-qs-s2").style.display = "none";
    document.getElementById("img-qs-s3").style.display = "none";
    document.getElementById("img-qs-s4").style.display = "none";
    document.getElementById("img-qs-s5").style.display = "none";
    document.getElementById("img-qs-s6").style.display = "none";
    document.getElementById("img-qs-s7").style.display = "none";
    document.getElementById("img-qs-s8").style.display = "block";
    var element = document.getElementById("boton-s1");
    element.classList.remove("active");
    var element = document.getElementById("boton-s2");
    element.classList.remove("active");
    var element = document.getElementById("boton-s3");
    element.classList.remove("active");
    var element = document.getElementById("boton-s4");
    element.classList.remove("active");
    var element = document.getElementById("boton-s5");
    element.classList.remove("active");
    var element = document.getElementById("boton-s6");
    element.classList.remove("active");
    var element = document.getElementById("boton-s7");
    element.classList.remove("active");
    var element = document.getElementById("boton-s8");
    element.classList.add("active");

};